# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c65cc560ced8fd93f480c4f438e278b328fd049236754716681b06b07b9f0176816178461f154ec68dad377480b125ab89b33da826fbfd99aa991d3ff343e3

test:
  secret_key_base: 17cca8ad05efefd6ee032e9d74d7bb908ad97ece7e6af614662fdb32bb58cfb1109062b00e089ffa724db3a318af7d57f992bfbe0a24b446afe6aca3eb42aebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
